### ISSUE TITLE
Error generating Component (Promise.binf(...))

### ISSUE THREAD

**Issue by EugeValeiras** [ng-tools/generator-ng-factory#10]
TypeError: Promise.bind(...).then is not a function
    at module.exports (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\app\actions\prompting\component.js:11:4)
    at C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\app\actions\prompting\index.js:115:43
    at tryCatcher (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\promise.js:581:18)
    at Async._drainQueue (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:UserseugenAppDataRoamingnpmnode_modulesgenerator-ng-factorynode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by EugeValeiras** [comment]
Note: Im using Windows
