### ISSUE TITLE
Generating application dependent issue

### ISSUE THREAD

**Issue by EugeValeiras** [ng-tools/generator-ng-factory#11]
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at readDestFileAsync (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\app\modules\generator.js:83:23)
    at Generator.writeAsync (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\app\modules\generator.js:198:10)
    at writeConfigFiles (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\app\actions\writing\index.js:14:23)
    at tryCatcher (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\promise.js:245:10)
    at Async._drainQueue (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\Users\eugen\AppData\Roaming\npm\node_modules\generator-ng-factory\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:UserseugenAppDataRoamingnpmnode_modulesgenerator-ng-factorynode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by EugeValeiras** [comment]
Note: Im using Windows
