### ISSUE TITLE
gulp serve broken

### ISSUE THREAD

**Issue by robshep** [ng-tools/generator-ng-factory#2]
New install, no readme so tried: 

`gulp serve`

Error show below.

Is there a readme of what to do after `yo ....` ?

`[12:04:22] Using gulpfile ~/Projects/MR/custfieldtest/gulpfile.js
[12:04:22] Starting 'serve'...
[12:04:22] Starting 'ng:serve'...
[12:04:22] Starting 'ng:beforeServe'...
[12:04:22] Finished 'ng:beforeServe' after 522 μs
[12:04:22] Starting 'ng:src/clean'...
[12:04:22] Finished 'ng:src/clean' after 5.25 ms
[12:04:22] Starting 'ng:src/views'...
[12:04:25] 'ng:src/views' errored after 2.92 s
[12:04:25] Error: Bower components directory does not exist at /Users/rob/Projects/MR/custfieldtest/app/bower_components
    at module.exports (/Users/rob/Projects/MR/custfieldtest/node_modules/factory-angular-channels/node_modules/main-bower-files/lib/index.js:54:15)
    at Object.module.exports (/Users/rob/Projects/MR/custfieldtest/node_modules/factory-angular-channels/lib/channels/index/src.js:38:17)
    at Object.<anonymous> (/Users/rob/Projects/MR/custfieldtest/node_modules/undertaker-app-tasks/lib/tasks/views.js:24:41)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at asyncRunner (/Users/rob/Projects/MR/custfieldtest/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
    at process._tickDomainCallback (node.js:381:11)
[12:04:25] 'ng:serve' errored after 2.93 s
[12:04:25] Error: Bower components directory does not exist at /Users/rob/Projects/MR/custfieldtest/app/bower_components
    at module.exports (/Users/rob/Projects/MR/custfieldtest/node_modules/factory-angular-channels/node_modules/main-bower-files/lib/index.js:54:15)
    at Object.module.exports (/Users/rob/Projects/MR/custfieldtest/node_modules/factory-angular-channels/lib/channels/index/src.js:38:17)
    at Object.<anonymous> (/Users/rob/Projects/MR/custfieldtest/node_modules/undertaker-app-tasks/lib/tasks/views.js:24:41)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at asyncRunner (/Users/rob/Projects/MR/custfieldtest/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
    at process._tickDomainCallback (node.js:381:11)
[12:04:25] 'serve' errored after 2.94 s
[12:04:25] Error: Bower components directory does not exist at /Users/rob/Projects/MR/custfieldtest/app/bower_components
    at module.exports (/Users/rob/Projects/MR/custfieldtest/node_modules/factory-angular-channels/node_modules/main-bower-files/lib/index.js:54:15)
    at Object.module.exports (/Users/rob/Projects/MR/custfieldtest/node_modules/factory-angular-channels/lib/channels/index/src.js:38:17)
    at Object.<anonymous> (/Users/rob/Projects/MR/custfieldtest/node_modules/undertaker-app-tasks/lib/tasks/views.js:24:41)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at asyncRunner (/Users/rob/Projects/MR/custfieldtest/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
    at process._tickDomainCallback (node.js:381:11)`

**Comment by mgcrea** [comment]
`bower i` should fix this.

**Comment by robshep** [comment]
ooops, I had no `bower`

figured `npm install yo` would drag in bower :/

    npm install -g bower
    bower install

fixed. Sorry, my bad.
