### ISSUE TITLE
gulp serve not working on a fresh project

### ISSUE THREAD

**Issue by mickael83** [ng-tools/generator-ng-factory#3]
Hi,

I am trying to use the ng-factory generator to scaffold a new project to build an angularjs component. After the project has been created with the **yo ng-factory** command, I tried to run it using the **gulp serve** task but found the following error:

```
[16:47:40] Using gulpfile ~/Downloads/bower-api-comum/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^
TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

```

Am I missing something? I already tried to run again the npm install && bower update with no luck.

Best regards,
Michael Pinheiro

**Comment by mgcrea** [comment]
You're trying to run a gulp4 project with a gulp3 global install.
Try `node_modules/.bin/gulp serve`

**Comment by mickael83** [comment]
Thanks for the quick answer :smile: It solves the problem.

Now I'm having the following errors, maybe some missing configuration. 

```
$ node_modules/.bin/gulp serve
[17:07:31] Using gulpfile ~/Downloads/bower-api-comum/gulpfile.js
[17:07:31] Starting 'serve'...
[17:07:31] Starting 'ng:serve'...
[17:07:31] Starting 'ng:beforeServe'...
[17:07:31] Finished 'ng:beforeServe' after 548 μs
[17:07:31] Starting 'ng:src/clean'...
[17:07:31] Finished 'ng:src/clean' after 4.02 ms
[17:07:31] Starting 'ng:src/views'...
[17:07:33] 'ng:src/views' errored after 1.89 s
[17:07:33] Error: Bower components directory does not exist at /home/mickael/Downloads/bower-api-comum/app/bower_components
    at Error (native)
    at module.exports (/home/mickael/Downloads/bower-api-comum/node_modules/factory-angular-channels/node_modules/main-bower-files/lib/index.js:75:71)
    at Object.module.exports (/home/mickael/Downloads/bower-api-comum/node_modules/factory-angular-channels/lib/channels/index/src.js:38:17)
    at Object.<anonymous> (/home/mickael/Downloads/bower-api-comum/node_modules/undertaker-app-tasks/lib/tasks/views.js:24:41)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at asyncRunner (/home/mickael/Downloads/bower-api-comum/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
    at process._tickDomainCallback (node.js:381:11)
[17:07:33] 'ng:serve' errored after 1.9 s
[17:07:33] Error: Bower components directory does not exist at /home/mickael/Downloads/bower-api-comum/app/bower_components
    at Error (native)
    at module.exports (/home/mickael/Downloads/bower-api-comum/node_modules/factory-angular-channels/node_modules/main-bower-files/lib/index.js:75:71)
    at Object.module.exports (/home/mickael/Downloads/bower-api-comum/node_modules/factory-angular-channels/lib/channels/index/src.js:38:17)
    at Object.<anonymous> (/home/mickael/Downloads/bower-api-comum/node_modules/undertaker-app-tasks/lib/tasks/views.js:24:41)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at asyncRunner (/home/mickael/Downloads/bower-api-comum/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
    at process._tickDomainCallback (node.js:381:11)
[17:07:33] 'serve' errored after 1.9 s
[17:07:33] Error: Bower components directory does not exist at /home/mickael/Downloads/bower-api-comum/app/bower_components
    at Error (native)
    at module.exports (/home/mickael/Downloads/bower-api-comum/node_modules/factory-angular-channels/node_modules/main-bower-files/lib/index.js:75:71)
    at Object.module.exports (/home/mickael/Downloads/bower-api-comum/node_modules/factory-angular-channels/lib/channels/index/src.js:38:17)
    at Object.<anonymous> (/home/mickael/Downloads/bower-api-comum/node_modules/undertaker-app-tasks/lib/tasks/views.js:24:41)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at asyncRunner (/home/mickael/Downloads/bower-api-comum/node_modules/gulp/node_modules/undertaker/node_modules/bach/node_modules/async-done/index.js:38:18)
    at process._tickDomainCallback (node.js:381:11)

```

Is there any place where I can find some documentation to avoid asking silly questions?

Thank you.

**Comment by mgcrea** [comment]
`bower i` should solve this.

**Comment by mickael83** [comment]
Well I managed to make it work by overriding the default cwd path like below.

```
// gulpfile.js

var options = {
  paths: {
    cwd: '.'
  }
};

var gulp = require('gulp');
var config = require('ng-factory').use(gulp, options);

...
```

I will really appreciate the FAQ.

Thanks again.
